name: Build Docker image
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t alingo:latest .

      - name: Tag Docker image with version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "tag version: $TAG_VERSION"
          repo=${{ github.repository }}
          lower_repo=$(echo "$repo" | tr '[:upper:]' '[:lower:]')
          docker tag alingo:latest ghcr.io/${lower_repo}:${TAG_VERSION}
          docker tag alingo:latest ghcr.io/${lower_repo}:latest

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image with version tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          repo=${{ github.repository }}
          lower_repo=$(echo "$repo" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${lower_repo}:${TAG_VERSION}
          docker push ghcr.io/${lower_repo}:latest